steps:
# Install dependencies
- name: 'python:3.11'
  entrypoint: pip
  args: ['install', '-r', 'requirements.txt']

# Run database migrations if needed
- name: 'python:3.11'
  entrypoint: python
  args: ['app/init_db.py']
  env:
  - 'DATABASE_URL=${_DATABASE_URL}'

# Deploy to App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--quiet']

substitutions:
  _DATABASE_URL: 'postgresql://username:password@/dbname?host=/cloudsql/PROJECT_ID:REGION:INSTANCE_NAME'

timeout: '1200s' 