[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements.txt && pip list | grep -i jinja"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
RAILWAY_ENVIRONMENT = "production" 